project_id = "fxfmswnvfqqdsgrcgvhl"

[functions.test-ai-provider]
verify_jwt = true

[functions.cleanup-notifications]
verify_jwt = true

[functions.fix-notification-links]
verify_jwt = true

[functions.notification-retry-system]
verify_jwt = true