project_id = "fxfmswnvfqqdsgrcgvhl"

[functions.test-ai-provider]
verify_jwt = false

[functions.cleanup-notifications]
verify_jwt = false

[functions.fix-notification-links]
verify_jwt = false

[functions.notification-retry-system]
verify_jwt = false

[functions.ensure-master-user]
verify_jwt = false