// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxfmswnvfqqdsgrcgvhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4Zm1zd252ZnFxZHNncmNndmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDE1NDEsImV4cCI6MjA3MzYxNzU0MX0.4a3CTyQoRUEHJubCoYRn79P2XDf1eMNGVGX2RLUPqcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});